### ISSUE TITLE
Verify all basic lands are known

### ISSUE THREAD

**Issue by PaleRiderNZ** [shawkinsl/mtga-tracker#78]
I get this error every time I enter the edit decklist step. For all decks.

![mtg tracker](https://user-images.githubusercontent.com/37426143/38077288-fd31f86c-3394-11e8-9c61-ada9e6e2bafb.png)

**Comment by shawkinsl** [comment]
Thanks very much! I think this is probably due to a custom art land that we don't know about yet. Would you mind sharing the export text of this deck? If you're not comfortable sharing the decklist, I think that just the landbase should be good. I'm guessing that there are 9 of (at least, and hopefully exactly) one type of land that I haven't seen yet.

**Comment by PaleRiderNZ** [comment]
I am using the full art lands which are (HOU) I'll get a list for you

**Comment by PaleRiderNZ** [comment]
1 Champion of Wits (HOU) 31
1 Nezahal, Primal Tide (RIX) 45
4 Ravenous Chupacabra (RIX) 82
1 Tetzimoc, Primal Death (RIX) 86
3 The Scarab God (HOU) 145
1 Treasure Map (XLN) 250
2 Opt (XLN) 65
4 Essence Scatter (AKH) 52
3 Cancel (AKH) 44
2 Hieroglyphic Illumination (AKH) 57
2 Secrets of the Golden City (RIX) 52
2 Supreme Will (HOU) 49
1 Pull from Tomorrow (AKH) 65
1 Moment of Craving (RIX) 79
3 Golden Demise (RIX) 73
2 Reaver Ambush (RIX) 83
2 Final Reward (AKH) 92
2 Desert of the Mindful (HOU) 173
3 Desert of the Glorified (HOU) 171
9 Island (HOU) 186
9 Swamp (AKH) 252
1 Arch of Orazca (RIX) 185
1 Field of Ruin (XLN) 254

**Comment by shawkinsl** [comment]
Thanks, that's definitely enough info. This was my bad for sure, pretty dumb of me to not expect people to want full arts, heh. I'm going to rename this ticket, and will definitely fix it ASAP tomorrow (sorry, it's very late here). Thanks again!

**Comment by PaleRiderNZ** [comment]
no problem, thank you :)

**Comment by shawkinsl** [comment]
I decided this was gonna bug me if I didn't fix it, it's a pretty glaring flaw. I'm going to work around it in #80 with a longer term fix living in this ticket and #79. Building you a release (0.3.0-beta) now, will upload as soon as I get through a quick smoke test.

**Comment by shawkinsl** [comment]
(Do you have a twitter account I can attribute for finding this bug in the release tweet? :) )

**Comment by PaleRiderNZ** [comment]
Sorry, no twitter :) good work!

**Comment by shawkinsl** [comment]
Here's the release! Thanks again for the report, please let me know if you still have any issues!
https://github.com/shawkinsl/mtga-tracker/releases/tag/0.3.0-beta

**Comment by PaleRiderNZ** [comment]
One issue I noticed was that my scarab gods were showing as scorpion gods
